name: local-stack

services:
  postgres:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: ams

  fs:
    image: chrislusf/seaweedfs:latest
    ports:
      - "9000:8333"
    environment:
      - AWS_ACCESS_KEY_ID=fsadmin
      - AWS_SECRET_ACCESS_KEY=fsadmin
    command: 'server -s3 -s3.port=8333 -dir=/data'
