"""delete_variant

Revision ID: 4aba176196e0
Revises: b7a32fa685d3
Create Date: 2026-07-22 16:44:34.941263

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4aba176196e0"
down_revision = "b7a32fa685d3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_variants_id"), table_name="variants")
    op.drop_table("variants")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "variants",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("publish_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column(
            "variant_set", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.Column(
            "variant_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["publish_id"],
            ["publishes.id"],
            name=op.f("variants_publish_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("variants_pkey")),
    )
    op.create_index(op.f("ix_variants_id"), "variants", ["id"], unique=False)
    # ### end Alembic commands ###
